name: Deploy Hugo Site to GitHub Pages
on:
  push:
    branches: [main]
# 권한 설정을 write로 변경하여 gh-pages 브랜치에 푸시할 수 있도록 함
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      # 모든 서브모듈(테마 등)과 함께 저장소 체크아웃
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      # Hugo 설정
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true

      # Hugo 빌드 - baseURL 명시적 지정 옵션 추가 가능
      # (config.toml에 이미 올바르게 설정되어 있다면 생략 가능)
      - name: Build
        run: hugo --minify
        # 필요시 다음과 같이 baseURL 명시적 지정:
        # run: hugo --minify --baseURL="https://사용자이름.github.io/저장소이름/"

      # GitHub Pages 배포 - SSH 키 설정 유지
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # external_repository 필드는 다른 저장소에 배포할 때만 사용
          # external_repository 필드 제거함
          publish_branch: gh-pages
          publish_dir: ./public
          full_commit_message: ${{ github.event.head_commit.message }}
